BOT_NAME = "hltv_scraper"
SPIDER_MODULES = ["hltv_scraper.spiders"]
NEWSPIDER_MODULE = "hltv_scraper.spiders"
USER_AGENT = "hltv_scraper (+https://www.hltv.org/)"
ROBOTSTXT_OBEY = False
DOWNLOAD_DELAY = 3
RANDOMIZE_DOWNLOAD_DELAY = True
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"
